WikiTitle = Wikis Pathfinder-fr
MainUrl = http://www.pathfinder-fr.org/Wiki/
ContactEmail = site@pathfinder-fr.org
SenderEmail = site@pathfinder-fr.org
ErrorsEmails = foo@example.com
SmtpServer = localhost
SmtpPort = 25
SmtpUsername = 
SmtpPassword = 
SmtpSsl = no
DefaultPage = MainPage
DateTimeFormat = dd'/'MM'/'yyyy' 'HH':'mm
DefaultLanguage = fr-FR
DefaultTimezone = 60
MaxRecentChangesToDisplay = 10
RssFeedsMode = Summary
EnableDoubleClickEditing = no
EnableSectionEditing = yes
EnablePageToolbar = yes
EnableViewPageCode = yes
EnablePageInfoDiv = no
DisableBreadcrumbsTrail = yes
AutoGeneratePageNames = no
ProcessSingleLineBreaks = no
UseVisualEditorAsDefault = no
KeptBackupNumber = -1
DisplayGravatars = yes
UsersCanRegister = yes
UsernameRegex = ^\w[\w\ !$@%^\.\(\)]{3,25}$
PasswordRegex = ^[.]{6,25}$
AccountActivationMode = EMAIL
UsersGroup = Users
AdministratorsGroup = WikiAdministrator
AnonymousGroup = Anonymous
DisableCaptchaControl = no
DisableConcurrentEditing = no
ChangeModerationMode = None
AllowedFileTypes = jpg|jpeg|gif|png|tif|tiff|bmp|svg|htm|html|zip|rar|pdf|txt|doc|xls|ppt|docx|xlsx|pptx
FileDownloadCountFilterMode = CountSpecifiedExtensions
FileDownloadCountFilter = zip|pdf
MaxFileSize = 10240
ScriptTagsAllowed = no
LoggingLevel = 3
MaxLogSize = 256
IpHostFilter = 
DisableAutomaticVersionCheck = no
DisableCache = no
CacheSize = 1000
CacheCutSize = 200
EnableViewStateCompression = yes
EnableHttpCompression = yes
DefaultPagesProvider = ScrewTurn.Wiki.PagesStorageProvider
DefaultUsersProvider = ScrewTurn.Wiki.UsersStorageProvider
DefaultFilesProvider = ScrewTurn.Wiki.FilesStorageProvider
DefaultCacheProvider = ScrewTurn.Wiki.CacheProvider
Theme-Pathfinder-RPG = v2
Theme-Golarion = v2
Theme-Aventures = v2
EnableSectionAnchors = yes
Theme = v2
Theme-Parties = v2
